[workspace]
members = [
    "morpheus-core",
    "morpheus-core-wasm",
    "morpheus-core-c-api",
    "morpheus-sdk",
]

# [patch.crates-io]
# iop-keyvault = { path="../keyvault-rs/keyvault" }
# iop-keyvault-wasm = { path="../keyvault-rs/keyvault-wasm" }

[patch.crates-io]
iop-keyvault = { git="https://github.com/Internet-of-People/keyvault-rust", branch="develop" }
iop-keyvault-wasm = { git="https://github.com/Internet-of-People/keyvault-rust", branch="develop" }
