[workspace]
members = [
    "coeus-node",
    "coeus-core-wasm",
    "coeus-proto",
    "hydra-proto",
    "hydra-sdk",
    "journal-proto",
    "json-digest",
    "keyvault",
    "keyvault-wasm",
    "morpheus-node",
    "morpheus-core-wasm",
    "morpheus-proto",
    "morpheus-sdk",
    "sdk",
    "sdk-ffi",
    "sdk-wasm",
    "vault"
]

# Experiment for optimizing WASM and FFI binary sizes
[profile.release]
lto = true
opt-level = 's'

[patch.crates-io]
iop-coeus-node = { path="./coeus-node" }
iop-coeus-core-wasm = { path = "./coeus-core-wasm" }
iop-coeus-proto = { path="./coeus-proto" }
iop-hydra-proto = { path="./hydra-proto" }
iop-hydra-sdk = { path="./hydra-sdk" }
iop-journal-proto = { path="./journal-proto" }
iop-keyvault = { path="./keyvault" }
iop-keyvault-wasm = { path="./keyvault-wasm" }
iop-morpheus-node = { path="./morpheus-node" }
iop-morpheus-core-wasm = { path = "./morpheus-core-wasm" }
iop-morpheus-proto = { path="./morpheus-proto" }
iop-morpheus-sdk = { path="./morpheus-sdk" }
iop-vault = { path="./vault" }
json-digest = { path="./json-digest" }
