# --- Overwritten values
edition = "2021"
use_small_heuristics = "Max"
fn_args_layout = "Compressed"
use_field_init_shorthand = true
use_try_shorthand = true
# --- Default values
# max_width = 100
# tab_spaces = 4

#unstable_features = true
#blank_lines_upper_bound = 3
#brace_style = "AlwaysNextLine"
#fn_single_line = true
#condense_wildcard_suffixes = true
#format_code_in_doc_comments = true
#imports_indent = "Visual"
#indent_style = "Visual"
#match_arm_blocks = false
#overflow_delimited_expr = true
#reorder_impl_items = true
#struct_field_align_threshold = 20
