[package]
name = "iop-morpheus-proto"
description = "Morpheus protocol definitions used on both node and sdk side of the IOP Stack™"

version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
iop-journal-proto = { workspace = true }
iop-keyvault = { workspace = true }
json-digest = { workspace = true }
jwt-compact = { workspace = true, features = ["std"] }
serde = { workspace = true }
serde_json = { workspace = true }
serde_str = { workspace = true }
