[package]
name = "iop-sdk-wasm"
version = "0.0.9"
authors = [
    "IOP Ventures LLC <dev@iop-ventures.com>",
    "Rache Bartmoss <bartmoss@tutanota.com>",
    "wigy <wigy_opensource_developer@yahoo.com>"
]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
iop-coeus-core-wasm = "*"
iop-morpheus-core-wasm = "*"
