[package]
name = "iop-sdk-wasm"
description = "WebAssembly bindings to the client SDK for the IOP Stack™"

version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = { workspace = true }
iop-hydra-proto = { workspace = true }
iop-hydra-sdk = { workspace = true }
iop-keyvault = { workspace = true }
iop-keyvault-wasm = { workspace = true }
iop-morpheus-proto = { workspace = true }
iop-morpheus-sdk = { workspace = true }
iop-proto-wasm = { workspace = true }
iop-vault = { workspace = true }
json-digest-wasm = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde-wasm-bindgen = { workspace = true }
serde_json = { workspace = true }
wasm-bindgen = { workspace = true }
