[package]
name = "iop-morpheus-sdk"
version = "0.0.1"
authors = ["IoP Ventures LLC <info@iop-ventures.com>", "Rache Bartmoss <bartmoss@tutanota.com>", "wigy <wigy_opensource_developer@yahoo.com>"]
license = "LGPL-3.0-or-later"
edition = "2018"


[lib]
name = "morpheus_sdk"
crate-type = ["rlib","cdylib"]


[dependencies]
async-trait = "*"
failure = "*"
futures = "*"
hyper = "*"
iop-keyvault = "0.0.2"
iop-morpheus-core = { path = "../morpheus-core" }
log = "*"
multihash = "*"
rand = "*"
serde = "*"
serde_bytes = "*"
serde_json = "*"
tiny-bip39 = { version = "0.7.3", default-features = false }
tokio = { version="*", features=["full"] }


[dev-dependencies]
tempfile = "*"


[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.5", default-features = false }
android_logger = "0.5"
