[package]
name = "iop-morpheus-core-wasm"
version = "0.0.1"
authors = ["IoP Ventures LLC <info@iop-ventures.com>", "Rache Bartmoss <bartmoss@tutanota.com>", "wigy <wigy_opensource_developer@yahoo.com>"]
edition = "2018"


[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
failure = "*"
iop-keyvault = { git="https://github.com/Internet-of-People/keyvault-rust", branch="develop" }
iop-keyvault-wasm = { git="https://github.com/Internet-of-People/keyvault-rust", branch="develop" }
iop-morpheus-core = { path = "../morpheus-core" }
log = "*"
serde_json = "*"
wasm-bindgen = { version = "*", features = ["serde-serialize"] }
