[package]
name = "morpheus-core-wasm"
version = "0.1.0"
authors = ["IoP Ventures LLC <info@iop-ventures.com>", "Rache Bartmoss <bartmoss@tutanota.com>", "wigy <wigy_opensource_developer@yahoo.com>"]
edition = "2018"


[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
failure = "*"
keyvault = { git = "https://github.com/Internet-of-People/mercury-rust", branch="develop" }
keyvault-wasm = { git = "https://github.com/Internet-of-People/mercury-rust", branch="develop" }
morpheus-core = { path = "../morpheus-core" }
log = "*"
serde_json = "*"
wasm-bindgen = { version = "*", features = ["serde-serialize"] }
