[package]
name = "iop-morpheus-core-wasm"
version = "0.0.4"
authors = ["IoP Ventures LLC <info@iop-ventures.com>", "Rache Bartmoss <bartmoss@tutanota.com>", "wigy <wigy_opensource_developer@yahoo.com>"]
edition = "2018"


[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
anyhow = "1.0.32"
iop-keyvault = "0.0.4"
iop-keyvault-wasm = "0.0.4"
iop-morpheus-core = "0.0.4"
json-digest = "0.0.5"
log = "0.4.11"
serde = "1.0.115"
serde_json = "1.0.57"
# TODO latest 0.2.66/67 does not work with recent wasm-opt
wasm-bindgen = { version = "=0.2.65", features = ["serde-serialize"] }
# wasm-bindgen-futures = "*"
