[package]
name = "json-digest"
description = "Allow selective masking of JSON subdocuments for privacy, preserving the digest of the whole document."
keywords = ["crypto", "iop", "privacy", "json", "digest"]
categories = ["cryptography", "algorithms"]

version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow = { workspace = true }
multibase = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tiny-keccak = { version = "2.0.2", features = ["sha3"] }
unicode-normalization = { version = "0.1.24" }

[dev-dependencies]
hex = { workspace = true }
