[package]
name = "iop-node-wasm"
description = "WebAssembly bindings to the node implementation for Hydraledger"

version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
iop-coeus-node = { workspace = true }
iop-coeus-proto = { workspace = true }
iop-journal-proto = { workspace = true }
iop-keyvault-wasm = { workspace = true }
iop-morpheus-node = { workspace = true }
iop-morpheus-proto = { workspace = true }
iop-proto-wasm = { workspace = true }
json-digest-wasm = { workspace = true }
serde = { workspace = true }
serde-wasm-bindgen = { workspace = true }
serde_json = { workspace = true }
wasm-bindgen = { workspace = true }
