[package]
name = "iop-journal-proto"
description = "Journal-independent abstract definitions for the IOP Stack™"

version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow = { workspace = true }
varint = { workspace = true }
