[package]
name = "iop-journal-proto"
version = "0.0.13"
authors = ["wigy <wigy_opensource_developer@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.32"
varint = "0.9.0"
