[package]
name = "iop-keyvault"
version = "0.0.4"
edition = "2018"
description = "A general-purpose hierarchical deterministic generator for asymmetric keys."
authors = ["IoP Ventures LLC <info@iop-ventures.com>", "wigy <wigy_opensource_developer@yahoo.com>", "Rache Bartmoss <bartmoss@tutanota.com>"]
license = "LGPL-3.0-or-later"
repository = "https://github.com/Internet-of-People/keyvault-rust"
homepage = "https://iop.global"
keywords = ["crypto", "wallet", "iop", "vault", "ssi"]
categories = ["cryptography", "cryptography::cryptocurrencies"]

[dependencies]
anyhow = "1.0.32"
blake2 = "0.9.0"
digest = "0.9.0"
ed25519-dalek = "1.0.0"
failure = "0.1.8"
rand = { version = "0.7.2", features = ["getrandom"] }
getrandom = "0.1.14"
hex = "0.4.2"
hmac = "0.9.0"
# Unfortunately the crate name of the libsecp256k1 collides with the perfect module name
# for the cipher, so we rename the dependency here:
secp = { version = "0.3.5", package = "libsecp256k1" }
multibase = "0.8.0"
orion = "0.15.2"
ripemd160 = "0.9.1"
serde = { version = "1.0.87", features = ["derive"] }
serde_bytes = "0.11.3"
sha2 = "0.9.1"
tiny-bip39 = { version = "0.7.3", features = [] }

[target.wasm32-unknown-unknown.dependencies.getrandom]
version = "0.1.14"
features = ["wasm-bindgen"]

[dev-dependencies]
rmp-serde = "0.14.3"
serde_json = "1.0.56"
