[package]
name = "iop-keyvault"
description = "A general-purpose hierarchical deterministic generator for asymmetric keys."
keywords = ["crypto", "wallet", "iop", "vault", "ssi"]
categories = ["cryptography", "cryptography::cryptocurrencies"]

version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow = { workspace = true }
blake2 = { workspace = true }
digest = { workspace = true }
ed25519-dalek = { workspace = true }
rand = { workspace = true }
getrandom = { workspace = true }
hex = { workspace = true }
hmac = { workspace = true }
# Unfortunately the crate name of the libsecp256k1 collides with the perfect module name
# for the cipher, so we rename the dependency here:
secp = { workspace = true }
multibase = { workspace = true }
orion = { workspace = true }
ripemd = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
sha2 = { workspace = true }
tiny-bip39 = { workspace = true }

[dev-dependencies]
rmp-serde = { workspace = true }
serde_json = { workspace = true }
