[package]
name = "iop-vault"
description = "A hierarchical deterministic wallet that allows plugin extensions for the IOP Stack™"

version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow = { workspace = true }
iop-keyvault = { workspace = true }
multibase = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true, features = ["rc"]}
typetag = { workspace = true }

# --- Hydra dependencies
byteorder = { workspace = true }
hex = { workspace = true }
sha2 = { workspace = true }

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.21.1", default-features = false }
android_logger = "0.15.1"
