[package]
name = "iop-morpheus-node"
description = "Morpheus layer-2 plugin implementation for Hydraledger"

version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
iop-hydra-proto = { workspace = true }
iop-journal-proto = { workspace = true }
iop-keyvault = { workspace = true }
iop-morpheus-proto = { workspace = true }
json-digest = { workspace = true }
jwt-compact = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_str = { workspace = true }


[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.21.1", default-features = false }
android_logger = "0.15.1"
