[package]
name = "iop-hydra-proto"
description = "Hydra-core specific protocol definitions for the IOP Stack™"

version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow = { workspace = true }
byteorder = { workspace = true }
hex = { workspace = true }
iop-coeus-proto = { workspace = true }
iop-journal-proto = { workspace = true }
iop-keyvault = { workspace = true }
iop-morpheus-proto = { workspace = true }
json-digest = { workspace = true }
num-derive = { version = "0.4.2" }
num-traits = { version = "0.2.19" }
rand = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
serde_str = { workspace = true }
sha2 = { workspace = true }
varint = { workspace = true }


[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.21.1", default-features = false }
android_logger = { version = "0.15.1" }
