[package]
name = "iop-hydra-sdk"
description = "Hydraledger specific modules for the IOP Stack™ SDK"

version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow = { workspace = true }
byteorder = { workspace = true }
hex = { workspace = true }
iop-hydra-proto = { workspace = true }
iop-keyvault = { workspace = true }
iop-morpheus-proto = { workspace = true }
iop-vault = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
typetag = { workspace = true }
varint = { workspace = true }


[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.21.1", default-features = false }
android_logger = "0.15.1"
