[package]
name = "iop-keyvault-wasm"
version = "0.0.2"
edition = "2018"
description = "WebAssembly wrappers for the iop-keyvault crate."
authors = ["IoP Ventures LLC <info@iop-ventures.com>", "wigy <wigy_opensource_developer@yahoo.com>", "Rache Bartmoss <bartmoss@tutanota.com>"]
license = "LGPL-3.0-or-later"
repository = "https://github.com/Internet-of-People/keyvault-rust"
homepage = "https://iop.global"
keywords = ["crypto", "wallet", "iop", "wasm", "ssi"]
categories = ["cryptography", "cryptography::cryptocurrencies", "wasm"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
failure = "0.1.8"
log = "0.4.11"
iop-keyvault = { path="../keyvault" }
serde_json = "1.0.56"
wasm-bindgen = { version = "0.2.65", features = ["serde-serialize"] }
