[package]
name = "iop-coeus-proto"
version = "0.0.13"
authors = ["IOP Ventures LLC <dev@iop-ventures.com>", "Rache Bartmoss <bartmoss@tutanota.com>", "wigy <wigy_opensource_developer@yahoo.com>"]
edition = "2018"
license = "LGPL-3.0-or-later"


[dependencies]
anyhow = "1.0.32"
iop-journal-proto = "0.0.13"
iop-keyvault = "0.0.13"
json-digest = "0.0.13"
serde = "1.0.115"
serde_bytes = "0.11.5"
serde_str = "0.1.0"
serde_json = "1.0.57"
