[package]
name = "iop-coeus-proto"
description = "Coeus protocol definitions used on both node and sdk side of the IOP Stack™"

version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow = { workspace = true }
iop-journal-proto = { workspace = true }
iop-keyvault = { workspace = true }
json-digest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_bytes = { workspace = true }
serde_str = { workspace = true }

[features]
did = []
